service: default
env: standard
runtime: nodejs22
automatic_scaling:
  target_cpu_utilization: 0.90
  min_instances: 0
  max_instances: 1
  max_concurrent_requests: 50

handlers:
  # Serve static assets (e.g., JS, CSS, images) from the dist directory
  - url: /static
    static_dir: dist/static

  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|ttf|woff|woff2|eot|json|txt))
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|jpg|jpeg|gif|ico|svg|ttf|woff|woff2|eot|json|txt)

  # Redirect all other routes to index.html for React Router
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
