service: default
env: standard
runtime: nodejs14
automatic_scaling:
  target_cpu_utilization: 0.90
  min_instances: 0
  max_instances: 1
  max_concurrent_requests: 50

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
