name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - "src/**"

jobs:
  setup-build-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Declare GitHub Hash and Branch
        id: vars
        shell: bash
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SA_EMAIL }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Build Fronted
        run: |
          export REACT_APP_VERSION=prod-${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}
          yarn install
          yarn build

      - id: "deploy"
        uses: google-github-actions/deploy-appengine@v1
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.PROJECT_ID }}
          version: "prod-${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}"
